export default {
    HOST_PEMBELAJARAN_SOSIAL: process.env.HOST_PEMBELAJARAN_SOSIAL,
    API_WEATHER_KEY: process.env.API_WEATHER_KEY,
    ELASTIC_APM_ENABLE: process.env.ELASTIC_APM_ENABLE === "false" ? false : true,
    ELASTIC_APM_ENVIRONMENT: process.env.ELASTIC_APM_ENVIRONMENT,
    ELASTIC_APM_LOG_LEVEL: process.env.ELASTIC_APM_LOG_LEVEL,
    ELASTIC_APM_LOGGER: process.env.ELASTIC_APM_LOGGER,
    ELASTIC_APM_SECRET_TOKEN: process.env.ELASTIC_APM_SECRET_TOKEN,
    ELASTIC_APM_SERVER_URL: process.env.ELASTIC_APM_SERVER_URL,
    ELASTIC_APM_SERVICE_NAME: process.env.ELASTIC_APM_SERVICE_NAME,
    ELASTIC_APM_API_KEY: process.env.ELASTIC_APM_API_KEY,
};
  