name: hoono-projects

services:
  app:
    build:
      context: .
      args:
        - PORT=${PORT}
    env_file:
      - .env
    networks:
      - dev
    depends_on:
      - redis
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hono-projects-data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: "redis:7.2.5-alpine"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  postgres-data: