-- UP  
CREATE TABLE users (  
  id SERIAL PRIMARY KEY,  
  nama VARCHAR(255) NOT NULL,  
  email VARCHAR(255) UNIQUE NOT NULL,  
  password VARCHAR(255) NOT NULL,  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
); 

-- DOWN
DROP TABLE users;